{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
<XML>
  <post>
    <retraction>
      <post_guid>{{$guid}}</post_guid>
      <type>{{$type}}</type>
      <diaspora_handle>{{$handle}}</diaspora_handle>
    </retraction>
  </post>
</XML>