{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
<h4>{{$user}}</h4>
	{{include file="field_radio.tpl" field=$page_normal}}
	{{include file="field_radio.tpl" field=$page_soapbox}}
	{{include file="field_radio.tpl" field=$page_freelove}}
<h4>{{$community}}</h4>
	{{include file="field_radio.tpl" field=$page_community}}
	{{include file="field_radio.tpl" field=$page_prvgroup}}
