<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(dirname(__FILE__)))."/library";
$baseDir = dirname($vendorDir);

return array(
    'HTMLPurifier' => array($vendorDir . '/ezyang/htmlpurifier/library'),
);
