{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
Oi, 
Eu sou {{$sitename}}   
Os desenvolvedores do friendica lançaram uma atualização {{$update}} recentemente, 
mas quando tentei instalá-la algo de errado aconeteceu.  
Isso precisa ser corrigido logo e não posso fazê-lo sozinho. Por favor contacte um 
desenvolvedor do friendica se você não puder fazer a correção. Meu banco de dados pode estar inválido. 

A mensagem de erro é : '{{$error}}'.   

Lamento. 
Seu servidor friendica em {{$siteurl}}