codecov:
  branch: develop
  ci:
    - ci.friendi.ca

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment: false
