{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
{{*<!--
<script type="text/javascript" src="js/country.min.js" ></script>

<script language="javascript" type="text/javascript">
	Fill_Country('{{$country_name}}');
	Fill_States('{{$region}}');
</script>
-->*}}
