{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
{{$myname}},

'{{$requestor}}' på {{$sitename}} vill följa dina uppdateringar här på Friendica.

Besök dennes profil på {{$url}}.

Logga in för att godkänna eller avslå förfrågan.

{{$siteurl}}

Hälsningar,
{{$sitename}} admin
