{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

<dfrn:relocate>

	<dfrn:url>{{$url}}</dfrn:url>
	<dfrn:name>{{$name}}</dfrn:name>
	<dfrn:photo>{{$photo}}</dfrn:photo>
	<dfrn:thumb>{{$thumb}}</dfrn:thumb>
	<dfrn:micro>{{$micro}}</dfrn:micro>
	<dfrn:request>{{$request}}</dfrn:request>
	<dfrn:confirm>{{$confirm}}</dfrn:confirm>
	<dfrn:notify>{{$notify}}</dfrn:notify>
	<dfrn:poll>{{$poll}}</dfrn:poll>
	<dfrn:sitepubkey>{{$sitepubkey}}</dfrn:sitepubkey>


</dfrn:relocate>

