{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
{{$vcard_widget}}
{{$follow_widget}}
{{$groups_widget}}
{{$findpeople_widget}}
{{$networks_widget}}

