{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

{{$preamble}}

{{if $content_allowed}}
{{$title}}

{{$textversion}}

{{/if}}
{{$tsitelink}}
{{$titemlink}}

{{$thanks}}
{{$site_admin}}


