{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
<div class="photos-upload-submit-wrapper" >
	<input type="submit" name="submit" value="{{$submit}}" id="photos-upload-submit" />
</div>
