{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

Drogi {{$myname}},

Masz nowego obserwującego na {{$sitename}} -  '{{$requestor}}'.

Możesz odwiedzić jego profil na {{$url}}.

Zaloguj się na swoją stronę by potwierdzić lub zignorować/anulować prośbę.

{{$siteurl}}

Pozdrawiam,

	{{$sitename}} Administrator