{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

Drogi {{$username}},

	Świetne wieści! '{{$fn}}' na '{{$dfrn_url}}' przyjął / przyjęła 
Twoją prośbę o znajomość na '{{$sitename}}'.

Jesteście teraz znajomymi i możecie wymieniać się zmianami statusów, zdjęciami i wiadomościami
bez ograniczeń.

Zajrzyj na stronę 'Kontakty' na {{$sitename}} jeśli chcesz dokonać 
zmian w tej relacji. 

{{$siteurl}}

[Możesz np.: utworzyć oddzielny profil z informacjami, który nie będzie
dostępny dla wszystkich - i przypisać sprawdzanie uprawnień do '{{$fn}}'].

Z poważaniem, 

	{{$sitename}} Administrator

 