{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

Drogi {{$username}},

	'{{$fn}}' w '{{$dfrn_url}}' zaakceptował 
twoje połączenie na '{{$sitename}}'.

	'{{$fn}}' zaakceptował Cię jako "fana", uniemożliwiając 
pewne sposoby komunikacji - takie jak prywatne wiadomości czy niektóre formy
interakcji pomiędzy profilami. Jeśli jest to strona gwiazdy lub  społeczności, ustawienia zostały
zastosowane automatycznie.

	'{{$fn}}' może rozszeżyć to w dwustronną komunikację lub więcej (doprecyzować) 
relacje w przyszłości. 

	Będziesz teraz otrzymywać aktualizacje statusu od '{{$fn}}', 
który będzie pojawiać się na Twojej stronie "Sieć"  

{{$siteurl}}

Z poważaniem,

	Administrator {{$sitename}}