{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

Nowy wniosek o rejestrację użytkownika wpłynął na {{$sitename}} i wymaga 
potwierdzenia. 


Oto szczegóły konta:

Pełna nazwa:»{{$username}}
Jesteś na:	{{$siteurl}}
Login:»{{$email}}


Aby potwierdzić rejestrację wejdź na:


{{$siteurl}}/regmod/allow/{{$hash}} 


Aby anulować rejestrację i usunąć konto wejdź na:


{{$siteurl}}/regmod/deny/{{$hash}}


Dziękuję.
