{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

Drogi/a {{$myname}},

Otrzymałeś właśnie zaproszenie do znajomych na stronie {{$sitename}} 

od '{{$requestor}}'.

Skorzystaj z tego linku, aby odwiedzić jego profil: {{$url}}.

Proszę się zalogować, aby zobaczyć pełen opis 
i zaakceptować lub zignorować / anulować.

{{$siteurl}}

Pozdrawiam

	{{$sitename}} administrator