{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

Góðan daginn {{$myname}},

Þú hefur nýjan aðdáanda frá {{$sitename}} - '{{$requestor}}'.

Þú getur heimsótt þeirra heimasvæði á {{$url}}.

Vinsamlegast innskráðu þig til að samþykkja eða hunsa/hætta við beiðni.

{{$siteurl}}

Bestu kveðjur,

	Kerfisstjóri {{$sitename}}