{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

Góðan daginn {{$username}}, 

	Frábærar fréttir... '{{$fn}}' hjá '{{$dfrn_url}}' hefur samþykkt 
tengibeiðni þína hjá '{{$sitename}}'.

Þið eruð nú sameiginlegir vinir og getið skipst á stöðu uppfærslum, myndum og tölvupósti
án hafta.

Endilega fara á síðunna 'Tengiliðir' á þjóninum {{$sitename}} ef þú villt gera 
einhverjar breytingar á þessu sambandi. 

{{$siteurl}}

[Til dæmis þá getur þú búið til nýjar notenda upplýsingar um þig, með ítarlegri lýsingu, sem eiga ekki
að vera aðgengileg almenningi - og veitt aðgang til að sjá '{{$fn}}'].

Bestu kveðjur,

	Kerfisstjóri {{$sitename}}

 