{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

Góðan daginn {{$username}},
	Takk fyrir að skrá þig á {{$sitename}}. Notandinn þinn hefur verið stofnaður. 
Innskráningar upplýsingarnar þínar eru eftirfarandi:


Vefþjónn:	{{$siteurl}}
Notendanafn:	{{$email}}
Aðgangsorð:	{{$password}}

Þú getur breytt aðgangsorðinu þínu á "Stillingar" síðunni eftir að þú hefur skráð þig 
inn.

Endilega eyddu smá tíma í að yfirfara aðrar notenda stillingar á þeirri síðu.

Einnig gætir þú bætt við grunnupplýsingum á sjálfgefna prófílinn 
(á "Forsíður" síðunni) svo aðrið geti auðveldlega fundið þig.

Við mælum með að þú setjir fullt nafn, bætir við prófíl mynd,
bætir nokkrum "leitarorðum" (mjög gagnlegt við að eignast nýja vini) og 
mögulega bætir við í hvaða landi þú býrð, ef þú villt ekki vera nákvæmari
en það.

Við virðum að fullu rétt þinn til einkalífs, því er ekkert að þessum atriðum skilyrði. 
Ef þú ert byrjandi og þekkir ekki einhvern hér, þér eru hér fólk
sem getur aðstoðað þig við að eignast nýja og áhugaverða vini.  


Takk fyrir og velkomin(n) á {{$sitename}}.

Bestu kveðjur,
	Kerfisstjóri {{$sitename}}

 