{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

Beiðni um nýjan notanda barst {{$sitename}} sem krefst 
þíns samþykkis. 


Innskráningar upplýsingarnar eru eftirfarandi:

Fullt nafn:	{{$username}}
Vefþjónn:	{{$siteurl}}
Notendanafn:	{{$email}}


Til að samþykkja beiðnina þarf að heimsækja eftirfarandi slóð:


{{$siteurl}}/regmod/allow/{{$hash}} 


Til að synja beiðni og eyða notanda þá heimsækir þú slóðina:


{{$siteurl}}/regmod/deny/{{$hash}}


Takk fyrir.
