{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
Hæ, 
Ég er {{$sitename}}.   
Þróunarteymi friendica gáfu nýlega út uppfærslu {{$update}}, 
En þegar ég reyndi að uppfæra, gerist eitthvað hræðilegt.  
Þetta þarf að laga strax og ég get það ekki ein.  Hafðu samband við 
þróunarteymi friendica ef þú getur ekki hjálpað mér.  Gagnagrunnurinn minn gæti verið skemmdur 

Villuskilaboðin eru '{{$error}}'.   

Fyrirgefðu, 
þinn friendica þjónn á {{$siteurl}}