{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
<script type="text/javascript" src="{{$baseurl}}/js/ajaxupload.min.js" ></script>

<script language="javascript" type="text/javascript">if(typeof window.jotInit != 'undefined') initEditor();</script>
