{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

<script>
	window.prevLink = "{{$prevlink}}";
	window.nextLink = "{{$nextlink}}";
	window.photoEdit = true;

</script>
