{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

<script language="javascript" type="text/javascript">
window.editSelect = "none";
window.jotId = "#prvmail-text";
window.imageUploadButton = 'prvmail-upload';
</script>

