{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
<!--[if IE]>
<script type="text/javascript" src="https://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
{{*<!--<script type="text/javascript" src="{{$baseurl}}/library/tinymce/jscripts/tiny_mce/tiny_mce.js" ></script>
<script type="text/javascript">
  tinyMCE.init({ mode : "none"});
</script>-->*}}
{{*<!--<script type="text/javascript" src="{{$baseurl}}/js/jquery.js" ></script>
<script type="text/javascript" src="{{$baseurl}}/view/theme/decaf-mobile/js/jquery.divgrow-1.3.1.f1.js" ></script>
<script type="text/javascript" src="{{$baseurl}}/js/jquery.textinputs.js" ></script>
<script type="text/javascript" src="{{$baseurl}}/view/theme/decaf-mobile/js/fk.autocomplete.js" ></script>-->*}}
{{*<!--<script type="text/javascript" src="{{$baseurl}}/library/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
<script type="text/javascript" src="{{$baseurl}}/library/colorbox/jquery.colorbox-min.js"></script>-->*}}
{{*<!--<script type="text/javascript" src="{{$baseurl}}/library/tiptip/jquery.tipTip.minified.js"></script>-->*}}
{{*<!--<script type="text/javascript" src="{{$baseurl}}/library/jgrowl/jquery.jgrowl_minimized.js"></script>
<script type="text/javascript" src="{{$baseurl}}/view/theme/decaf-mobile/js/acl.js" ></script>
<script type="text/javascript" src="{{$baseurl}}/js/webtoolkit.base64.js" ></script>
<script type="text/javascript" src="{{$baseurl}}/view/theme/decaf-mobile/js/main.js" ></script>-->*}}
<script type="text/javascript" src="{{$baseurl}}/view/theme/decaf-mobile/js/theme.js"></script>

<!--<script type="text/javascript" src="{{$baseurl}}/view/theme/decaf-mobile/js/jquery.package.js" ></script>
<script type="text/javascript" src="{{$baseurl}}/view/theme/decaf-mobile/js/decaf-mobile.package.js" ></script>-->

