{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
{{*<!--<link rel="stylesheet" href="{{$baseurl}}/view/theme/frost-mobile/login-style.css" type="text/css" media="all" />-->*}}

