{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

<script language="javascript" type="text/javascript">
{{*/*	window.nickname = "{{$nickname}}";
	window.linkURL = "{{$linkurl}}";
	var plaintext = "none";
	window.autocompleteType = 'msg-header';*/*}}
	window.jotId = "#prvmail-text";
	window.imageUploadButton = 'prvmail-upload';
</script>

