{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
{{if $classtoday}}
<script>
	$(document).ready(function() {{$lbr}}
		$('#events-reminder').addClass($.trim('{{$classtoday}}'));
	{{$rbr}});
</script>
{{/if}}

