name: Transifex
on: [push, pull_request]

jobs:
  messages:
    name: Check messages.po changes
    runs-on: ubuntu-latest
    steps:
      - name: Install gettext
        run: sudo apt-get install gettext

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Xgettext
        run: ./bin/run_xgettext.sh

      - name: Check if messages.po needs an update
        run: |
          echo "::group::Check messages.po"
          # Skip first 4 lines in possible diff, because they're header
          # Skip all lines of the git diff starting with "@@" or comments or starting "POT-Creation-Date"
          if [[ $(git diff -U0 ./view/lang/C/messages.po | awk '!/@@|-"POT-Creation-Date|+"POT-Creation-Date|-#|+#/{print }' | wc -l) > 4 ]]; then
            echo "::error file=messages.po::messages.po is out of date"
            exit 1
          else
            echo "Nothing to update"
          fi
          echo "::endgroup::"
        shell: bash
