{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
<script language="javascript" type="text/javascript"
          src="{{$baseurl}}/library/fullcalendar/fullcalendar.min.js"></script>

<script language="javascript" type="text/javascript">
eventInitEditor();
</script>

