{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

尊敬的{{$username}},

	精彩新闻... 「{{$fn}}」在「{{$dfrn_url}}」接受了 
您的连通要求在「{{$sitename}}」。

您们现在是共同的朋友们，会兑换现状更新，照片和邮件
无限

请看您的联络页在{{$sitename}}如果您想做 
什么变化关于这个关系。 

{{$siteurl}}

[例如，您会想造成区分的简介括无
公开－和分配看权利给「{{$fn}}」

谨上,

	{{$sitename}}行政人员

 