{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

尊敬的{{$username}},

	「{{$fn}}」在「{{$dfrn_url}}」接受了 
您的联络要求在「{{$sitename}}」

	「{{$fn}}」接受您为迷。这限制 
有的种类沟通，例如私人信息和简介
操作。如果这是名人或社会页，这些设置是
自动地应用。

	「{{$fn}}」会将来选择延长关系成双向的或更允许的 
关系。 

	您会开始受到公开的现状更新从「{{$fn}}」， 
它们出现在您的「网络」页在  

{{$siteurl}}

谨上，

	{{$sitename}}行政人员