{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

尊敬的{{$username}}，
	{{$sitename}}最近收到一个要求复位您的账户 
密码。为肯定这个要求，请点击肯定按钮
在下边或粘贴在您的游览器地址条 

如果您没有要求这个变化，请别点击这个按努i
和不理或删除这个邮件。 

您密码没有被变化直到我们证实您
发送这个要求时。 

点击这个按钮为证实您的同一个人：

{{$reset_link}}

然后您收到后续通信包括新密码。

您会变化密码在您的账户设置页登记后。

登记细节是：

网站位置:	{{$siteurl}}
登记名:	{{$email}}




谨上，
	{{$sitename}}行政人员

 