{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

尊敬的{{$username}}。
	您的随您要求密码变化了。请保持这 
信息为您的备案(或立即变化您的密码成 
什么容易记住)。


您的登记信息是：

网站位置:	{{$siteurl}}
登记名:	{{$email}}
密码:	{{$new_password}}

您会变化这个密码在您的账户设置页登记后。


谨上，
	{{$sitename}}行政人员

 